name: Build & Push to GCR

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: buoyant-road-354520
          image_name: test-gcr
          image_tag: latest,${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
          dockerfile: ./Dockerfile